on:
  push:
    branches:
      - development

jobs:
  build:
    name: Compile id.tonomy smart contract
    runs-on: ubuntu-20.04
    container: eosio/eosio.cdt:v1.8.1

    steps:
      - uses: actions/checkout@v3

      - name: Build id.tonomy contract
        run: ./contracts/id.tonomy/build.sh local

      - name: Add built contracts to artifacts
        uses: actions/upload-artifact@v3
        with:
          name: id.tonomy
          path: ./contracts/id.tonomy

  deploy-staging:
    name: Deploy id.tonomy contract to staging
    needs: build
    runs-on: ubuntu-20.04
    container: eosio/eosio:v2.0.13

    steps:
      - name: Get built contracts from cache
        uses: actions/download-artifact@v3
        with:
          name: id.tonomy
          path: contracts/id.tonomy

      - name: Deploy id.tonomy contract
        run: |
          PKEY_EOSIO="PVT_K1_2bfGi9rYsXQSXXTvJbDAPhHLQUojjaNLomdm3cEJ1XTzMqUt3V"
          cleos wallet create --file ./wallet.txt
          cleos wallet import --private-key $PKEY_EOSIO
          cleos -u "https://blockchain-api-staging.tonomy.foundation" set contract id.tonomy ./contracts/id.tonomy id.tonomy.wasm id.tonomy.abi

  build-eosio:
    name: Compile eosio.boot and eosio.bios contracts
    runs-on: ubuntu-20.04
    container: eosio/eosio.cdt:v1.8.1

    steps:
      - uses: actions/checkout@v3

      - name: Build eosio.boot contract
        run: ./contracts/eosio.boot/build.sh local

      - name: Build eosio.bios contract
        run: ./contracts/eosio.bios/build.sh local

      - name: Add eosio.boot contracts to artifacts
        uses: actions/upload-artifact@v3
        with:
          name: eosio.boot
          path: ./contracts/eosio.boot

      - name: Add eosio.bios contracts to artifacts
        uses: actions/upload-artifact@v3
        with:
          name: eosio.bios
          path: ./contracts/eosio.bios

  push-docker:
    name: Builds docker image and push to Docker Hub
    needs: build-eosio
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3

      - name: Get eosio.boot contracts from cache
        uses: actions/download-artifact@v3
        with:
          name: eosio.boot
          path: contracts/eosio.boot

      - name: Get eosio.bios contracts from cache
        uses: actions/download-artifact@v3
        with:
          name: eosio.bios
          path: contracts/eosio.bios

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./blockchain/Dockerfile
          target: tonomy_blockchain_nodejs
          push: true
          tags: tonomy/blockchain:nodejs-development
