name: Compile all smart contracts

on:
  pull_request:
    branches:
      - master
      - testnet
      - development
      
jobs:
  compile:
    runs-on: ubuntu-20.04
    container: tonomy/antelope

    steps:
      - uses: actions/checkout@v3

      - name: Compile demo.tmy
        run: ./contracts/demo.tmy/build.sh local
      
      - name: Compile eosio.bios
        run: ./contracts/eosio.bios/build.sh local

      - name: Compile eosio.boot
        run: ./contracts/eosio.boot/build.sh local

      - name: Compile eosio.msig
        run: ./contracts/eosio.msig/build.sh local

      - name: Compile eosio.token
        run: ./contracts/eosio.token/build.sh local

      - name: Compile eosio.tonomy
        run: ./contracts/eosio.tonomy/build.sh local

      - name: Compile tonomy
        run: ./contracts/tonomy/build.sh local

      - name: Compile vesting.tmy
        run: ./contracts/vesting.tmy/build.sh local
